git-svn-id: https://svn.qdecoder.org/qdecoder/trunk@213 5a34604f-89d6-db11-b6c0-0015c5f490bc

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1275,8 +1275,10 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+  --enable-debug          enable debugging print out
   --enable-64bit          enable 64 bit supports
-  --enable-mysql          enable MySQL database supports
+  --enable-mysql=/MYSQL_INCLUDE_DIR_PATH/
+                          enable MySQL database supports
   --disable-cgisupport    exclude CGI related APIs
   --disable-configparser  exclude configuration file parser & string parser
                           APIs
@@ -4156,24 +4158,18 @@ fi
 
 fi
 
-
-
-for ac_header in mysql.h hello.h
-do
-as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
-if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
-  { echo "$as_me:$LINENO: checking for $ac_header" >&5
-echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6; }
-if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+if test "${ac_cv_header_sys_sendfile_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for sys/sendfile.h" >&5
+echo $ECHO_N "checking for sys/sendfile.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_sys_sendfile_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 fi
-ac_res=`eval echo '${'$as_ac_Header'}'`
-	       { echo "$as_me:$LINENO: result: $ac_res" >&5
-echo "${ECHO_T}$ac_res" >&6; }
+{ echo "$as_me:$LINENO: result: $ac_cv_header_sys_sendfile_h" >&5
+echo "${ECHO_T}$ac_cv_header_sys_sendfile_h" >&6; }
 else
   # Is the header compilable?
-{ echo "$as_me:$LINENO: checking $ac_header usability" >&5
-echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6; }
+{ echo "$as_me:$LINENO: checking sys/sendfile.h usability" >&5
+echo $ECHO_N "checking sys/sendfile.h usability... $ECHO_C" >&6; }
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -4181,7 +4177,7 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 $ac_includes_default
-#include <$ac_header>
+#include <sys/sendfile.h>
 _ACEOF
 rm -f conftest.$ac_objext
 if { (ac_try="$ac_compile"
@@ -4213,15 +4209,15 @@ rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 echo "${ECHO_T}$ac_header_compiler" >&6; }
 
 # Is the header present?
-{ echo "$as_me:$LINENO: checking $ac_header presence" >&5
-echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6; }
+{ echo "$as_me:$LINENO: checking sys/sendfile.h presence" >&5
+echo $ECHO_N "checking sys/sendfile.h presence... $ECHO_C" >&6; }
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <$ac_header>
+#include <sys/sendfile.h>
 _ACEOF
 if { (ac_try="$ac_cpp conftest.$ac_ext"
 case "(($ac_try" in
@@ -4254,25 +4250,25 @@ echo "${ECHO_T}$ac_header_preproc" >&6; }
 # So?  What about this header?
 case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
   yes:no: )
-    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the compiler's result" >&5
-echo "$as_me: WARNING: $ac_header: proceeding with the compiler's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/sendfile.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: sys/sendfile.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/sendfile.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: sys/sendfile.h: proceeding with the compiler's result" >&2;}
     ac_header_preproc=yes
     ;;
   no:yes:* )
-    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
-echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header:     check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: $ac_header:     check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header: see the Autoconf documentation" >&5
-echo "$as_me: WARNING: $ac_header: see the Autoconf documentation" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&5
-echo "$as_me: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header: in the future, the compiler will take precedence" >&5
-echo "$as_me: WARNING: $ac_header: in the future, the compiler will take precedence" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/sendfile.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: sys/sendfile.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/sendfile.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: sys/sendfile.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/sendfile.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: sys/sendfile.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/sendfile.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: sys/sendfile.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/sendfile.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: sys/sendfile.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/sendfile.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: sys/sendfile.h: in the future, the compiler will take precedence" >&2;}
     ( cat <<\_ASBOX
 ## --------------------------------------- ##
 ## Report this to http://www.qdecoder.org/ ##
@@ -4281,26 +4277,18 @@ _ASBOX
      ) | sed "s/^/$as_me: WARNING:     /" >&2
     ;;
 esac
-{ echo "$as_me:$LINENO: checking for $ac_header" >&5
-echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6; }
-if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+{ echo "$as_me:$LINENO: checking for sys/sendfile.h" >&5
+echo $ECHO_N "checking for sys/sendfile.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_sys_sendfile_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  eval "$as_ac_Header=\$ac_header_preproc"
+  ac_cv_header_sys_sendfile_h=$ac_header_preproc
 fi
-ac_res=`eval echo '${'$as_ac_Header'}'`
-	       { echo "$as_me:$LINENO: result: $ac_res" >&5
-echo "${ECHO_T}$ac_res" >&6; }
-
-fi
-if test `eval echo '${'$as_ac_Header'}'` = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
-_ACEOF
+{ echo "$as_me:$LINENO: result: $ac_cv_header_sys_sendfile_h" >&5
+echo "${ECHO_T}$ac_cv_header_sys_sendfile_h" >&6; }
 
 fi
 
-done
 
 
 ## Checks for typedefs, structures, and compiler characteristics.
@@ -4434,104 +4422,24 @@ fi
 ## Checks for libraries.
 
 ## Checks for library functions.
-
-
-for ac_func in socket sendfile
-do
-as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
-{ echo "$as_me:$LINENO: checking for $ac_func" >&5
-echo $ECHO_N "checking for $ac_func... $ECHO_C" >&6; }
-if { as_var=$as_ac_var; eval "test \"\${$as_var+set}\" = set"; }; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-/* Define $ac_func to an innocuous variant, in case <limits.h> declares $ac_func.
-   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
-#define $ac_func innocuous_$ac_func
-
-/* System header to define __stub macros and hopefully few prototypes,
-    which can conflict with char $ac_func (); below.
-    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
-    <limits.h> exists even on freestanding compilers.  */
-
-#ifdef __STDC__
-# include <limits.h>
-#else
-# include <assert.h>
-#endif
-
-#undef $ac_func
-
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-char $ac_func ();
-/* The GNU C library defines this for functions which it implements
-    to always fail with ENOSYS.  Some functions are actually named
-    something starting with __ and the normal name is an alias.  */
-#if defined __stub_$ac_func || defined __stub___$ac_func
-choke me
-#endif
-
-int
-main ()
-{
-return $ac_func ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_c_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest$ac_exeext &&
-       $as_test_x conftest$ac_exeext; then
-  eval "$as_ac_var=yes"
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	eval "$as_ac_var=no"
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
-      conftest$ac_exeext conftest.$ac_ext
-fi
-ac_res=`eval echo '${'$as_ac_var'}'`
-	       { echo "$as_me:$LINENO: result: $ac_res" >&5
-echo "${ECHO_T}$ac_res" >&6; }
-if test `eval echo '${'$as_ac_var'}'` = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
-_ACEOF
-
-fi
-done
-
+#AC_CHECK_FUNCS([socket sendfile, dkdkdk])
 
 ## Set additional arguments
 opt_defs=""
+
+
+	# Check whether --enable-debug was given.
+if test "${enable_debug+set}" = set; then
+  enableval=$enable_debug;
+else
+  enableval=no
+fi
+
+	if test "$enableval" = yes; then
+		{ echo "$as_me:$LINENO: 'debug' feature is enabled" >&5
+echo "$as_me: 'debug' feature is enabled" >&6;}
+		opt_defs="$opt_defs -DBUILD_DEBUG"
+	fi
 
 
 	# Check whether --enable-64bit was given.
@@ -4542,21 +4450,57 @@ else
 fi
 
 	if test "$enableval" = yes; then
+		{ echo "$as_me:$LINENO: '64bit' feature is enabled" >&5
+echo "$as_me: '64bit' feature is enabled" >&6;}
 		opt_defs="$opt_defs -D_GNU_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64"
 	fi
 
 
-	# Check whether --enable-mysql was given.
+# Check whether --enable-mysql was given.
 if test "${enable_mysql+set}" = set; then
-  enableval=$enable_mysql;
+  enableval=$enable_mysql; enableval=yes
+else
+  enableval=no
+fi
+
+if test "$enableval" = yes; then
+	as_ac_File=`echo "ac_cv_file_$enable_mysql/mysql.h" | $as_tr_sh`
+{ echo "$as_me:$LINENO: checking for $enable_mysql/mysql.h" >&5
+echo $ECHO_N "checking for $enable_mysql/mysql.h... $ECHO_C" >&6; }
+if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "$enable_mysql/mysql.h"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+ac_res=`eval echo '${'$as_ac_File'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  enableval=yes
 else
   enableval=no
 fi
 
 	if test "$enableval" = yes; then
-		opt_defs="$opt_defs -DWITH_MYSQL"
+		{ echo "$as_me:$LINENO: 'mysql' feature is enabled" >&5
+echo "$as_me: 'mysql' feature is enabled" >&6;}
+		opt_defs="$opt_defs -DENABLE_MYSQL -I$enable_mysql"
+	else
+		{ { echo "$as_me:$LINENO: error: can't find 'mysql.h' header in '$enable_mysql' directory
+See \`config.log' for more details." >&5
+echo "$as_me: error: can't find 'mysql.h' header in '$enable_mysql' directory
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
 	fi
-
+fi
 #todo MYSQL_INCLUDE
 
 
@@ -4568,7 +4512,9 @@ else
 fi
 
 	if test "$enableval" = no; then
-		opt_defs="$opt_defs -DWITHOUT_CGISUPPORT"
+		{ echo "$as_me:$LINENO: 'cgisupport' feature is disabled" >&5
+echo "$as_me: 'cgisupport' feature is disabled" >&6;}
+		opt_defs="$opt_defs -DDISABLE_CGISUPPORT"
 	fi
 
 
@@ -4580,7 +4526,9 @@ else
 fi
 
 	if test "$enableval" = no; then
-		opt_defs="$opt_defs -DWITHOUT_CONFIGPARSER"
+		{ echo "$as_me:$LINENO: 'configparser' feature is disabled" >&5
+echo "$as_me: 'configparser' feature is disabled" >&6;}
+		opt_defs="$opt_defs -DDISABLE_CONFIGPARSER"
 	fi
 
 
@@ -4592,7 +4540,9 @@ else
 fi
 
 	if test "$enableval" = no; then
-		opt_defs="$opt_defs -DWITHOUT_ARG"
+		{ echo "$as_me:$LINENO: 'arg' feature is disabled" >&5
+echo "$as_me: 'arg' feature is disabled" >&6;}
+		opt_defs="$opt_defs -DDISABLE_ARG"
 	fi
 
 
@@ -4604,7 +4554,9 @@ else
 fi
 
 	if test "$enableval" = no; then
-		opt_defs="$opt_defs -DWITHOUT_AWK"
+		{ echo "$as_me:$LINENO: 'awk' feature is disabled" >&5
+echo "$as_me: 'awk' feature is disabled" >&6;}
+		opt_defs="$opt_defs -DDISABLE_AWK"
 	fi
 
 
@@ -4616,7 +4568,9 @@ else
 fi
 
 	if test "$enableval" = no; then
-		opt_defs="$opt_defs -DWITHOUT_SED"
+		{ echo "$as_me:$LINENO: 'sed' feature is disabled" >&5
+echo "$as_me: 'sed' feature is disabled" >&6;}
+		opt_defs="$opt_defs -DDISABLE_SED"
 	fi
 
 
@@ -4628,7 +4582,9 @@ else
 fi
 
 	if test "$enableval" = no; then
-		opt_defs="$opt_defs -DWITHOUT_IPC"
+		{ echo "$as_me:$LINENO: 'ipc' feature is disabled" >&5
+echo "$as_me: 'ipc' feature is disabled" >&6;}
+		opt_defs="$opt_defs -DDISABLE_IPC"
 	fi
 
 
@@ -4640,7 +4596,9 @@ else
 fi
 
 	if test "$enableval" = no; then
-		opt_defs="$opt_defs -DWITHOUT_SOCKET"
+		{ echo "$as_me:$LINENO: 'socket' feature is disabled" >&5
+echo "$as_me: 'socket' feature is disabled" >&6;}
+		opt_defs="$opt_defs -DDISABLE_SOCKET"
 	fi
 
 
@@ -4652,7 +4610,9 @@ else
 fi
 
 	if test "$enableval" = no; then
-		opt_defs="$opt_defs -DWITHOUT_HASHTBL"
+		{ echo "$as_me:$LINENO: 'hashtbl' feature is disabled" >&5
+echo "$as_me: 'hashtbl' feature is disabled" >&6;}
+		opt_defs="$opt_defs -DDISABLE_HASHTBL"
 	fi
 
 
@@ -4664,7 +4624,9 @@ else
 fi
 
 	if test "$enableval" = no; then
-		opt_defs="$opt_defs -DWITHOUT_OBSTACK"
+		{ echo "$as_me:$LINENO: 'obstack' feature is disabled" >&5
+echo "$as_me: 'obstack' feature is disabled" >&6;}
+		opt_defs="$opt_defs -DDISABLE_OBSTACK"
 	fi
 
 
@@ -4676,7 +4638,9 @@ else
 fi
 
 	if test "$enableval" = no; then
-		opt_defs="$opt_defs -DWITHOUT_LOG"
+		{ echo "$as_me:$LINENO: 'log' feature is disabled" >&5
+echo "$as_me: 'log' feature is disabled" >&6;}
+		opt_defs="$opt_defs -DDISABLE_LOG"
 	fi
 
 
