git-svn-id: https://svn.qdecoder.org/qdecoder/trunk@575 5a34604f-89d6-db11-b6c0-0015c5f490bc

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -339,7 +339,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S SET_MAKE RANLIB ac_ct_RANLIB AR CHMOD LD RM CPP EGREP OPT_DEFS OPT_INCS OPT_LIBS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S SET_MAKE RANLIB ac_ct_RANLIB AR CHMOD LD RM CPP EGREP LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1375,6 +1375,11 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
                               ac_config_files="$ac_config_files Makefile src/Makefile examples/Makefile"
 
 
+## Set path
+PATH="$PATH:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"
+CPPFLAGS="$CPPFLAGS -I/usr/include -I/usr/local/include -I./ -D_GNU_SOURCE"
+LDFLAGS="$LDFLAGS -L/usr/lib -L/usr/local/lib"
+
 ## Set autoconf setting
 #AC_CANONICAL_TARGET
 
@@ -2312,7 +2317,7 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 if test $ac_compiler_gnu = yes; then
-	CFLAGS="$CFLAGS -Wall -fPIC"
+	CFLAGS="-Wall -fPIC"
 #else
 #	AC_MSG_FAILURE([GCC is required to compile qDecoder.])
 fi
@@ -3818,11 +3823,6 @@ fi
 ## Checks for library functions.
 #AC_CHECK_FUNCS([socket sendfile])
 
-## Set additional arguments
-opt_defs=""
-opt_incs=""
-opt_libs=""
-
 
 	# Check whether --enable-debug or --disable-debug was given.
 if test "${enable_debug+set}" = set; then
@@ -3834,8 +3834,14 @@ fi;
 	if test "$enableval" = yes; then
 		{ echo "$as_me:$LINENO: 'debug' feature is enabled" >&5
 echo "$as_me: 'debug' feature is enabled" >&6;}
-		opt_defs="$opt_defs -DBUILD_DEBUG"
+		CPPFLAGS="$CPPFLAGS -DBUILD_DEBUG"
 	fi
+
+if test "$enableval" = yes; then
+	CFLAGS="$CFLAGS -g -O2"
+else
+	CFLAGS="$CFLAGS -O2"
+fi
 
 
 	# Check whether --enable-threadsafe or --disable-threadsafe was given.
@@ -3848,13 +3854,82 @@ fi;
 	if test "$enableval" = yes; then
 		{ echo "$as_me:$LINENO: 'threadsafe' feature is enabled" >&5
 echo "$as_me: 'threadsafe' feature is enabled" >&6;}
-		opt_defs="$opt_defs -DENABLE_THREADSAFE"
+		CPPFLAGS="$CPPFLAGS -DENABLE_THREADSAFE"
 	fi
 
 if test "$enableval" = yes; then
-	{ echo "$as_me:$LINENO: 'threadsafe' feature is enabled" >&5
-echo "$as_me: 'threadsafe' feature is enabled" >&6;}
-	opt_libs="$opt_libs -lpthread"
+
+echo "$as_me:$LINENO: checking for main in -lpthread" >&5
+echo $ECHO_N "checking for main in -lpthread... $ECHO_C" >&6
+if test "${ac_cv_lib_pthread_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lpthread  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_pthread_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_pthread_main=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_pthread_main" >&5
+echo "${ECHO_T}$ac_cv_lib_pthread_main" >&6
+if test $ac_cv_lib_pthread_main = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBPTHREAD 1
+_ACEOF
+
+  LIBS="-lpthread $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: Can't find pthread library." >&5
+echo "$as_me: error: Can't find pthread library." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 fi
 
 
@@ -3868,7 +3943,7 @@ fi;
 	if test "$enableval" = yes; then
 		{ echo "$as_me:$LINENO: 'lfs' feature is enabled" >&5
 echo "$as_me: 'lfs' feature is enabled" >&6;}
-		opt_defs="$opt_defs -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64"
+		CPPFLAGS="$CPPFLAGS -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64"
 	fi
 
 #Q_ARG_ENABLE([sendfile], [use sendfile() if possible], [-DENABLE_SENDFILE])
@@ -3908,8 +3983,7 @@ fi
 	if test "$enableval" = yes; then
 		{ echo "$as_me:$LINENO: 'fastcgi' feature is enabled" >&5
 echo "$as_me: 'fastcgi' feature is enabled" >&6;}
-		opt_defs="$opt_defs -DENABLE_FASTCGI"
-		opt_incs="$opt_incs -I$enable_fastcgi"
+		CPPFLAGS="$CPPFLAGS -DENABLE_FASTCGI -I$enable_fastcgi"
 	else
 		{ { echo "$as_me:$LINENO: error: can't find 'fcgi_stdio.h' header file in '$enable_fastcgi' directory. can't enable fastcgi support.
 See \`config.log' for more details." >&5
@@ -3954,8 +4028,7 @@ fi
 	if test "$enableval" = yes; then
 		{ echo "$as_me:$LINENO: 'mysql' feature is enabled" >&5
 echo "$as_me: 'mysql' feature is enabled" >&6;}
-		opt_defs="$opt_defs -DENABLE_MYSQL"
-		opt_incs="$opt_incs -I$enable_mysql"
+		CPPFLAGS="$CPPFLAGS -DENABLE_MYSQL -I$enable_mysql"
 	else
 		{ { echo "$as_me:$LINENO: error: can't find 'mysql.h' header file in '$enable_mysql' directory. can't enable mysql support.
 See \`config.log' for more details." >&5
@@ -3976,7 +4049,7 @@ fi;
 	if test "$enableval" = no; then
 		{ echo "$as_me:$LINENO: 'cgi' feature is disabled" >&5
 echo "$as_me: 'cgi' feature is disabled" >&6;}
-		opt_defs="$opt_defs -DDISABLE_CGI"
+		CPPFLAGS="$CPPFLAGS -DDISABLE_CGI"
 	fi
 
 
@@ -3990,7 +4063,7 @@ fi;
 	if test "$enableval" = no; then
 		{ echo "$as_me:$LINENO: 'socket' feature is disabled" >&5
 echo "$as_me: 'socket' feature is disabled" >&6;}
-		opt_defs="$opt_defs -DDISABLE_SOCKET"
+		CPPFLAGS="$CPPFLAGS -DDISABLE_SOCKET"
 	fi
 
 
@@ -4004,7 +4077,7 @@ fi;
 	if test "$enableval" = no; then
 		{ echo "$as_me:$LINENO: 'ipc' feature is disabled" >&5
 echo "$as_me: 'ipc' feature is disabled" >&6;}
-		opt_defs="$opt_defs -DDISABLE_IPC"
+		CPPFLAGS="$CPPFLAGS -DDISABLE_IPC"
 	fi
 
 
@@ -4018,18 +4091,15 @@ fi;
 	if test "$enableval" = no; then
 		{ echo "$as_me:$LINENO: 'datastructure' feature is disabled" >&5
 echo "$as_me: 'datastructure' feature is disabled" >&6;}
-		opt_defs="$opt_defs -DDISABLE_DATASTRUCTURE"
+		CPPFLAGS="$CPPFLAGS -DDISABLE_DATASTRUCTURE"
 	fi
 
 
-{ echo "$as_me:$LINENO: optional flags: $opt_defs $opt_incs $opt_libs" >&5
-echo "$as_me: optional flags: $opt_defs $opt_incs $opt_libs" >&6;}
-OPT_DEFS=$opt_defs
-
-OPT_INCS=$opt_incs
-
-OPT_LIBS=$opt_libs
-
+{ echo "$as_me:$LINENO: CFLAGS $CFLAGS" >&5
+echo "$as_me: CFLAGS $CFLAGS" >&6;}
+{ echo "$as_me:$LINENO: CPPFLAGS $CPPFLAGS" >&5
+echo "$as_me: CPPFLAGS $CPPFLAGS" >&6;}
+#AC_MSG_NOTICE([LIBS $LIBS])
 
 ## Create Makefile
 cat >confcache <<\_ACEOF
@@ -4665,9 +4735,6 @@ s,@LD@,$LD,;t t
 s,@RM@,$RM,;t t
 s,@CPP@,$CPP,;t t
 s,@EGREP@,$EGREP,;t t
-s,@OPT_DEFS@,$OPT_DEFS,;t t
-s,@OPT_INCS@,$OPT_INCS,;t t
-s,@OPT_LIBS@,$OPT_LIBS,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
